# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addcellsdialog.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DialogAddCells(object):
    def setupUi(self, DialogAddCells):
        DialogAddCells.setObjectName("DialogAddCells")
        DialogAddCells.resize(529, 234)
        self.formLayout = QtWidgets.QFormLayout(DialogAddCells)
        self.formLayout.setObjectName("formLayout")
        self.label_6 = QtWidgets.QLabel(DialogAddCells)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.txtCellsStore = QtWidgets.QLineEdit(DialogAddCells)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtCellsStore.sizePolicy().hasHeightForWidth())
        self.txtCellsStore.setSizePolicy(sizePolicy)
        self.txtCellsStore.setMinimumSize(QtCore.QSize(0, 0))
        self.txtCellsStore.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.txtCellsStore.setObjectName("txtCellsStore")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txtCellsStore)
        self.buttonBox = QtWidgets.QDialogButtonBox(DialogAddCells)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.SpanningRole, self.buttonBox)
        self.label_7 = QtWidgets.QLabel(DialogAddCells)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.spnPassageStore = QtWidgets.QSpinBox(DialogAddCells)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spnPassageStore.sizePolicy().hasHeightForWidth())
        self.spnPassageStore.setSizePolicy(sizePolicy)
        self.spnPassageStore.setProperty("value", 1)
        self.spnPassageStore.setObjectName("spnPassageStore")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spnPassageStore)
        self.label = QtWidgets.QLabel(DialogAddCells)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label)
        self.txtInitials = QtWidgets.QLineEdit(DialogAddCells)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtInitials.sizePolicy().hasHeightForWidth())
        self.txtInitials.setSizePolicy(sizePolicy)
        self.txtInitials.setMaximumSize(QtCore.QSize(30, 16777215))
        self.txtInitials.setObjectName("txtInitials")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.txtInitials)
        self.label_2 = QtWidgets.QLabel(DialogAddCells)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.txtDate = QtWidgets.QLineEdit(DialogAddCells)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtDate.sizePolicy().hasHeightForWidth())
        self.txtDate.setSizePolicy(sizePolicy)
        self.txtDate.setObjectName("txtDate")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.txtDate)
        self.label_3 = QtWidgets.QLabel(DialogAddCells)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.txtComments = QtWidgets.QLineEdit(DialogAddCells)
        self.txtComments.setMinimumSize(QtCore.QSize(250, 0))
        self.txtComments.setObjectName("txtComments")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.txtComments)

        self.retranslateUi(DialogAddCells)
        self.buttonBox.accepted.connect(DialogAddCells.accept)
        self.buttonBox.rejected.connect(DialogAddCells.reject)
        QtCore.QMetaObject.connectSlotsByName(DialogAddCells)

    def retranslateUi(self, DialogAddCells):
        _translate = QtCore.QCoreApplication.translate
        DialogAddCells.setWindowTitle(_translate("DialogAddCells", "Add Cells"))
        self.label_6.setText(_translate("DialogAddCells", "Cell Type"))
        self.label_7.setText(_translate("DialogAddCells", "Passage"))
        self.label.setText(_translate("DialogAddCells", "Initials"))
        self.label_2.setText(_translate("DialogAddCells", "Date"))
        self.txtDate.setInputMask(_translate("DialogAddCells", "99/99/9999"))
        self.label_3.setText(_translate("DialogAddCells", "Comments"))

