# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainInterface.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1387, 1002)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tab = QtWidgets.QTabWidget(self.centralwidget)
        self.tab.setStyleSheet("QTabWidget::tab-bar{\n"
"alignment: left;\n"
"}")
        self.tab.setUsesScrollButtons(False)
        self.tab.setDocumentMode(False)
        self.tab.setTabsClosable(False)
        self.tab.setMovable(False)
        self.tab.setObjectName("tab")
        self.tabDatabase = QtWidgets.QWidget()
        self.tabDatabase.setObjectName("tabDatabase")
        self.formLayout = QtWidgets.QFormLayout(self.tabDatabase)
        self.formLayout.setObjectName("formLayout")
        self.label_17 = QtWidgets.QLabel(self.tabDatabase)
        self.label_17.setObjectName("label_17")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label_17)
        self.txtDatabaseLocation = QtWidgets.QLineEdit(self.tabDatabase)
        self.txtDatabaseLocation.setMaximumSize(QtCore.QSize(250, 16777215))
        self.txtDatabaseLocation.setObjectName("txtDatabaseLocation")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.txtDatabaseLocation)
        self.label_18 = QtWidgets.QLabel(self.tabDatabase)
        self.label_18.setObjectName("label_18")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.txtUsername = QtWidgets.QLineEdit(self.tabDatabase)
        self.txtUsername.setObjectName("txtUsername")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.txtUsername)
        self.label_19 = QtWidgets.QLabel(self.tabDatabase)
        self.label_19.setObjectName("label_19")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.txtPassword = QtWidgets.QLineEdit(self.tabDatabase)
        self.txtPassword.setObjectName("txtPassword")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.txtPassword)
        self.checkBox = QtWidgets.QCheckBox(self.tabDatabase)
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.SpanningRole, self.checkBox)
        self.checkBox_2 = QtWidgets.QCheckBox(self.tabDatabase)
        self.checkBox_2.setChecked(True)
        self.checkBox_2.setObjectName("checkBox_2")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.SpanningRole, self.checkBox_2)
        self.checkBox_3 = QtWidgets.QCheckBox(self.tabDatabase)
        self.checkBox_3.setChecked(True)
        self.checkBox_3.setObjectName("checkBox_3")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.SpanningRole, self.checkBox_3)
        self.label_20 = QtWidgets.QLabel(self.tabDatabase)
        self.label_20.setObjectName("label_20")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.txtDatabaseName = QtWidgets.QLineEdit(self.tabDatabase)
        self.txtDatabaseName.setObjectName("txtDatabaseName")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.txtDatabaseName)
        self.bttnConnect = QtWidgets.QPushButton(self.tabDatabase)
        self.bttnConnect.setObjectName("bttnConnect")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.bttnConnect)
        self.tab.addTab(self.tabDatabase, "")
        self.tabStore = QtWidgets.QWidget()
        self.tabStore.setObjectName("tabStore")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.tabStore)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.entryFrame = QtWidgets.QFrame(self.tabStore)
        self.entryFrame.setObjectName("entryFrame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.entryFrame)
        self.gridLayout_3.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout_3.setContentsMargins(1, -1, 1, -1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.cmbDewarStore = QtWidgets.QComboBox(self.entryFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbDewarStore.sizePolicy().hasHeightForWidth())
        self.cmbDewarStore.setSizePolicy(sizePolicy)
        self.cmbDewarStore.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.cmbDewarStore.setObjectName("cmbDewarStore")
        self.cmbDewarStore.addItem("")
        self.cmbDewarStore.addItem("")
        self.gridLayout_3.addWidget(self.cmbDewarStore, 3, 1, 1, 1, QtCore.Qt.AlignLeft)
        self.label_8 = QtWidgets.QLabel(self.entryFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setWordWrap(True)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 2, 0, 1, 1)
        self.spnNumberStore = QtWidgets.QSpinBox(self.entryFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spnNumberStore.sizePolicy().hasHeightForWidth())
        self.spnNumberStore.setSizePolicy(sizePolicy)
        self.spnNumberStore.setMaximum(300)
        self.spnNumberStore.setProperty("value", 1)
        self.spnNumberStore.setObjectName("spnNumberStore")
        self.gridLayout_3.addWidget(self.spnNumberStore, 2, 1, 1, 1)
        self.bttnFindStorage = QtWidgets.QPushButton(self.entryFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bttnFindStorage.sizePolicy().hasHeightForWidth())
        self.bttnFindStorage.setSizePolicy(sizePolicy)
        self.bttnFindStorage.setAutoDefault(False)
        self.bttnFindStorage.setDefault(False)
        self.bttnFindStorage.setObjectName("bttnFindStorage")
        self.gridLayout_3.addWidget(self.bttnFindStorage, 2, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.entryFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 3, 0, 1, 1, QtCore.Qt.AlignRight)
        self.gridLayout_3.setColumnStretch(0, 1)
        self.gridLayout_8.addWidget(self.entryFrame, 0, 0, 1, 2, QtCore.Qt.AlignLeft)
        self.tblStoreCells = QtWidgets.QTableView(self.tabStore)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tblStoreCells.sizePolicy().hasHeightForWidth())
        self.tblStoreCells.setSizePolicy(sizePolicy)
        self.tblStoreCells.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.tblStoreCells.setSortingEnabled(True)
        self.tblStoreCells.setObjectName("tblStoreCells")
        self.gridLayout_8.addWidget(self.tblStoreCells, 1, 0, 1, 2)
        self.emailWidget = QtWidgets.QWidget(self.tabStore)
        self.emailWidget.setObjectName("emailWidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.emailWidget)
        self.horizontalLayout_5.setContentsMargins(-1, -1, 1, -1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.txtEmailStore = QtWidgets.QLineEdit(self.emailWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtEmailStore.sizePolicy().hasHeightForWidth())
        self.txtEmailStore.setSizePolicy(sizePolicy)
        self.txtEmailStore.setMinimumSize(QtCore.QSize(200, 0))
        self.txtEmailStore.setObjectName("txtEmailStore")
        self.horizontalLayout_5.addWidget(self.txtEmailStore, 0, QtCore.Qt.AlignLeft)
        self.bttnEmailPositionsStore = QtWidgets.QPushButton(self.emailWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bttnEmailPositionsStore.sizePolicy().hasHeightForWidth())
        self.bttnEmailPositionsStore.setSizePolicy(sizePolicy)
        self.bttnEmailPositionsStore.setObjectName("bttnEmailPositionsStore")
        self.horizontalLayout_5.addWidget(self.bttnEmailPositionsStore)
        self.gridLayout_8.addWidget(self.emailWidget, 4, 0, 1, 2, QtCore.Qt.AlignLeft)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.BttnBoxStore = QtWidgets.QDialogButtonBox(self.tabStore)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BttnBoxStore.sizePolicy().hasHeightForWidth())
        self.BttnBoxStore.setSizePolicy(sizePolicy)
        self.BttnBoxStore.setOrientation(QtCore.Qt.Horizontal)
        self.BttnBoxStore.setStandardButtons(QtWidgets.QDialogButtonBox.Apply|QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Close|QtWidgets.QDialogButtonBox.Reset)
        self.BttnBoxStore.setCenterButtons(False)
        self.BttnBoxStore.setObjectName("BttnBoxStore")
        self.horizontalLayout_3.addWidget(self.BttnBoxStore, 0, QtCore.Qt.AlignRight)
        self.gridLayout_8.addLayout(self.horizontalLayout_3, 5, 0, 1, 2)
        self.functionsWidget = QtWidgets.QWidget(self.tabStore)
        self.functionsWidget.setObjectName("functionsWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.functionsWidget)
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.bttnSelectAllStore = QtWidgets.QPushButton(self.functionsWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bttnSelectAllStore.sizePolicy().hasHeightForWidth())
        self.bttnSelectAllStore.setSizePolicy(sizePolicy)
        self.bttnSelectAllStore.setObjectName("bttnSelectAllStore")
        self.horizontalLayout_2.addWidget(self.bttnSelectAllStore, 0, QtCore.Qt.AlignLeft)
        self.bttnDeselectAllStore = QtWidgets.QPushButton(self.functionsWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bttnDeselectAllStore.sizePolicy().hasHeightForWidth())
        self.bttnDeselectAllStore.setSizePolicy(sizePolicy)
        self.bttnDeselectAllStore.setObjectName("bttnDeselectAllStore")
        self.horizontalLayout_2.addWidget(self.bttnDeselectAllStore)
        self.bttnAnotherPositionStore = QtWidgets.QPushButton(self.functionsWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bttnAnotherPositionStore.sizePolicy().hasHeightForWidth())
        self.bttnAnotherPositionStore.setSizePolicy(sizePolicy)
        self.bttnAnotherPositionStore.setObjectName("bttnAnotherPositionStore")
        self.horizontalLayout_2.addWidget(self.bttnAnotherPositionStore, 0, QtCore.Qt.AlignLeft)
        self.bttnNewCane = QtWidgets.QPushButton(self.functionsWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bttnNewCane.sizePolicy().hasHeightForWidth())
        self.bttnNewCane.setSizePolicy(sizePolicy)
        self.bttnNewCane.setObjectName("bttnNewCane")
        self.horizontalLayout_2.addWidget(self.bttnNewCane, 0, QtCore.Qt.AlignLeft)
        self.bttnStore = QtWidgets.QPushButton(self.functionsWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bttnStore.sizePolicy().hasHeightForWidth())
        self.bttnStore.setSizePolicy(sizePolicy)
        self.bttnStore.setObjectName("bttnStore")
        self.horizontalLayout_2.addWidget(self.bttnStore, 0, QtCore.Qt.AlignLeft)
        self.lblSelectedStoreLabel = QtWidgets.QLabel(self.functionsWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblSelectedStoreLabel.sizePolicy().hasHeightForWidth())
        self.lblSelectedStoreLabel.setSizePolicy(sizePolicy)
        self.lblSelectedStoreLabel.setText("")
        self.lblSelectedStoreLabel.setTextFormat(QtCore.Qt.PlainText)
        self.lblSelectedStoreLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblSelectedStoreLabel.setObjectName("lblSelectedStoreLabel")
        self.horizontalLayout_2.addWidget(self.lblSelectedStoreLabel, 0, QtCore.Qt.AlignLeft)
        self.lblSelectedStore = QtWidgets.QLabel(self.functionsWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblSelectedStore.sizePolicy().hasHeightForWidth())
        self.lblSelectedStore.setSizePolicy(sizePolicy)
        self.lblSelectedStore.setText("")
        self.lblSelectedStore.setObjectName("lblSelectedStore")
        self.horizontalLayout_2.addWidget(self.lblSelectedStore, 0, QtCore.Qt.AlignLeft)
        self.gridLayout_8.addWidget(self.functionsWidget, 2, 0, 1, 2, QtCore.Qt.AlignLeft)
        self.gridWidget = QtWidgets.QWidget(self.tabStore)
        self.gridWidget.setObjectName("gridWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridWidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.gridWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 0, 1, 1)
        self.spnPassageStore = QtWidgets.QSpinBox(self.gridWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spnPassageStore.sizePolicy().hasHeightForWidth())
        self.spnPassageStore.setSizePolicy(sizePolicy)
        self.spnPassageStore.setProperty("value", 1)
        self.spnPassageStore.setObjectName("spnPassageStore")
        self.gridLayout_2.addWidget(self.spnPassageStore, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridWidget)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 3, 1, 1)
        self.txtDate = QtWidgets.QLineEdit(self.gridWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtDate.sizePolicy().hasHeightForWidth())
        self.txtDate.setSizePolicy(sizePolicy)
        self.txtDate.setMaximumSize(QtCore.QSize(100, 16777215))
        self.txtDate.setObjectName("txtDate")
        self.gridLayout_2.addWidget(self.txtDate, 1, 4, 1, 1)
        self.txtInitials = QtWidgets.QLineEdit(self.gridWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtInitials.sizePolicy().hasHeightForWidth())
        self.txtInitials.setSizePolicy(sizePolicy)
        self.txtInitials.setMaximumSize(QtCore.QSize(30, 16777215))
        self.txtInitials.setObjectName("txtInitials")
        self.gridLayout_2.addWidget(self.txtInitials, 0, 4, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 1, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.gridWidget)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 2, 0, 1, 1)
        self.txtComments = QtWidgets.QLineEdit(self.gridWidget)
        self.txtComments.setMinimumSize(QtCore.QSize(150, 0))
        self.txtComments.setMaximumSize(QtCore.QSize(300, 16777215))
        self.txtComments.setObjectName("txtComments")
        self.gridLayout_2.addWidget(self.txtComments, 2, 1, 1, 1)
        self.bttnAddCells = QtWidgets.QPushButton(self.gridWidget)
        self.bttnAddCells.setObjectName("bttnAddCells")
        self.gridLayout_2.addWidget(self.bttnAddCells, 2, 4, 1, 1)
        self.combo_CellType = QtWidgets.QComboBox(self.gridWidget)
        self.combo_CellType.setObjectName("combo_CellType")
        self.gridLayout_2.addWidget(self.combo_CellType, 0, 1, 1, 1)
        self.gridLayout_8.addWidget(self.gridWidget, 3, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.tab.addTab(self.tabStore, "")
        self.tabRetreive = QtWidgets.QWidget()
        self.tabRetreive.setObjectName("tabRetreive")
        self.gridLayout = QtWidgets.QGridLayout(self.tabRetreive)
        self.gridLayout.setObjectName("gridLayout")
        self.tblRetreiveCells = QtWidgets.QTableView(self.tabRetreive)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tblRetreiveCells.sizePolicy().hasHeightForWidth())
        self.tblRetreiveCells.setSizePolicy(sizePolicy)
        self.tblRetreiveCells.setSortingEnabled(True)
        self.tblRetreiveCells.setObjectName("tblRetreiveCells")
        self.gridLayout.addWidget(self.tblRetreiveCells, 1, 0, 1, 2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.bttnBoxRetreive = QtWidgets.QDialogButtonBox(self.tabRetreive)
        self.bttnBoxRetreive.setStandardButtons(QtWidgets.QDialogButtonBox.Apply|QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Close|QtWidgets.QDialogButtonBox.Reset)
        self.bttnBoxRetreive.setObjectName("bttnBoxRetreive")
        self.horizontalLayout_6.addWidget(self.bttnBoxRetreive, 0, QtCore.Qt.AlignRight)
        self.gridLayout.addLayout(self.horizontalLayout_6, 4, 0, 1, 2)
        self.formWidget = QtWidgets.QWidget(self.tabRetreive)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.formWidget.sizePolicy().hasHeightForWidth())
        self.formWidget.setSizePolicy(sizePolicy)
        self.formWidget.setObjectName("formWidget")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.formWidget)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_3 = QtWidgets.QLabel(self.formWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_8.addWidget(self.label_3)
        self.txtCellsRetreive = QtWidgets.QLineEdit(self.formWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtCellsRetreive.sizePolicy().hasHeightForWidth())
        self.txtCellsRetreive.setSizePolicy(sizePolicy)
        self.txtCellsRetreive.setObjectName("txtCellsRetreive")
        self.horizontalLayout_8.addWidget(self.txtCellsRetreive)
        self.bttnFindCells = QtWidgets.QPushButton(self.formWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bttnFindCells.sizePolicy().hasHeightForWidth())
        self.bttnFindCells.setSizePolicy(sizePolicy)
        self.bttnFindCells.setObjectName("bttnFindCells")
        self.horizontalLayout_8.addWidget(self.bttnFindCells)
        self.chkTrash = QtWidgets.QCheckBox(self.formWidget)
        self.chkTrash.setObjectName("chkTrash")
        self.horizontalLayout_8.addWidget(self.chkTrash)
        self.gridLayout.addWidget(self.formWidget, 0, 0, 1, 1)
        self.horizontalWidget_2 = QtWidgets.QWidget(self.tabRetreive)
        self.horizontalWidget_2.setObjectName("horizontalWidget_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalWidget_2)
        self.horizontalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.bttnSelectAllRetreive = QtWidgets.QPushButton(self.horizontalWidget_2)
        self.bttnSelectAllRetreive.setObjectName("bttnSelectAllRetreive")
        self.horizontalLayout_4.addWidget(self.bttnSelectAllRetreive, 0, QtCore.Qt.AlignLeft)
        self.bttnDeselectAllRetreive = QtWidgets.QPushButton(self.horizontalWidget_2)
        self.bttnDeselectAllRetreive.setObjectName("bttnDeselectAllRetreive")
        self.horizontalLayout_4.addWidget(self.bttnDeselectAllRetreive, 0, QtCore.Qt.AlignLeft)
        self.bttnRetreive = QtWidgets.QPushButton(self.horizontalWidget_2)
        self.bttnRetreive.setObjectName("bttnRetreive")
        self.horizontalLayout_4.addWidget(self.bttnRetreive, 0, QtCore.Qt.AlignLeft)
        self.lblSelectedRetreiveLabel = QtWidgets.QLabel(self.horizontalWidget_2)
        self.lblSelectedRetreiveLabel.setText("")
        self.lblSelectedRetreiveLabel.setObjectName("lblSelectedRetreiveLabel")
        self.horizontalLayout_4.addWidget(self.lblSelectedRetreiveLabel)
        self.lblSelectedRetreive = QtWidgets.QLabel(self.horizontalWidget_2)
        self.lblSelectedRetreive.setText("")
        self.lblSelectedRetreive.setObjectName("lblSelectedRetreive")
        self.horizontalLayout_4.addWidget(self.lblSelectedRetreive)
        self.gridLayout.addWidget(self.horizontalWidget_2, 2, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.horizontalWidget_4 = QtWidgets.QWidget(self.tabRetreive)
        self.horizontalWidget_4.setObjectName("horizontalWidget_4")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalWidget_4)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.txtEmailRetreive = QtWidgets.QLineEdit(self.horizontalWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtEmailRetreive.sizePolicy().hasHeightForWidth())
        self.txtEmailRetreive.setSizePolicy(sizePolicy)
        self.txtEmailRetreive.setMinimumSize(QtCore.QSize(200, 0))
        self.txtEmailRetreive.setObjectName("txtEmailRetreive")
        self.horizontalLayout_7.addWidget(self.txtEmailRetreive, 0, QtCore.Qt.AlignLeft)
        self.bttnEmailPositionsRetreive = QtWidgets.QPushButton(self.horizontalWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bttnEmailPositionsRetreive.sizePolicy().hasHeightForWidth())
        self.bttnEmailPositionsRetreive.setSizePolicy(sizePolicy)
        self.bttnEmailPositionsRetreive.setObjectName("bttnEmailPositionsRetreive")
        self.horizontalLayout_7.addWidget(self.bttnEmailPositionsRetreive, 0, QtCore.Qt.AlignLeft)
        self.gridLayout.addWidget(self.horizontalWidget_4, 3, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.tab.addTab(self.tabRetreive, "")
        self.tabScheme = QtWidgets.QWidget()
        self.tabScheme.setObjectName("tabScheme")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tabScheme)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.horizontalWidget = QtWidgets.QWidget(self.tabScheme)
        self.horizontalWidget.setObjectName("horizontalWidget")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.horizontalWidget)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_14 = QtWidgets.QLabel(self.horizontalWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_11.addWidget(self.label_14)
        self.combo_Dewar = QtWidgets.QComboBox(self.horizontalWidget)
        self.combo_Dewar.setEditable(False)
        self.combo_Dewar.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.combo_Dewar.setObjectName("combo_Dewar")
        self.combo_Dewar.addItem("")
        self.combo_Dewar.addItem("")
        self.horizontalLayout_11.addWidget(self.combo_Dewar, 0, QtCore.Qt.AlignLeft)
        self.gridLayout_6.addWidget(self.horizontalWidget, 0, 0, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_13 = QtWidgets.QLabel(self.tabScheme)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_10.addWidget(self.label_13)
        self.lblChanges = QtWidgets.QLabel(self.tabScheme)
        self.lblChanges.setObjectName("lblChanges")
        self.horizontalLayout_10.addWidget(self.lblChanges)
        self.gridLayout_6.addLayout(self.horizontalLayout_10, 2, 0, 1, 1)
        self.gridWidget_2 = QtWidgets.QWidget(self.tabScheme)
        self.gridWidget_2.setObjectName("gridWidget_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridWidget_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.lblBlue = QtWidgets.QLabel(self.gridWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblBlue.sizePolicy().hasHeightForWidth())
        self.lblBlue.setSizePolicy(sizePolicy)
        self.lblBlue.setAutoFillBackground(False)
        self.lblBlue.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblBlue.setObjectName("lblBlue")
        self.gridLayout_5.addWidget(self.lblBlue, 0, 0, 1, 1)
        self.lblGreen = QtWidgets.QLabel(self.gridWidget_2)
        self.lblGreen.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblGreen.setObjectName("lblGreen")
        self.gridLayout_5.addWidget(self.lblGreen, 1, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.gridWidget_2)
        self.frame.setMinimumSize(QtCore.QSize(75, 0))
        self.frame.setStyleSheet("background-color: yellow\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_5.addWidget(self.frame, 0, 1, 1, 1, QtCore.Qt.AlignLeft)
        self.frame_2 = QtWidgets.QFrame(self.gridWidget_2)
        self.frame_2.setMinimumSize(QtCore.QSize(75, 0))
        self.frame_2.setStyleSheet("background-color: chartreuse")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_5.addWidget(self.frame_2, 1, 1, 1, 1, QtCore.Qt.AlignLeft)
        self.gridLayout_6.addWidget(self.gridWidget_2, 3, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.tabScheme)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Apply|QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_6.addWidget(self.buttonBox, 4, 1, 1, 1, QtCore.Qt.AlignRight)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_11 = QtWidgets.QLabel(self.tabScheme)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_4.addWidget(self.label_11, 0, 1, 1, 1)
        self.bttnDeleteID = QtWidgets.QPushButton(self.tabScheme)
        self.bttnDeleteID.setObjectName("bttnDeleteID")
        self.gridLayout_4.addWidget(self.bttnDeleteID, 3, 2, 1, 1, QtCore.Qt.AlignLeft)
        self.bttnNewColor = QtWidgets.QPushButton(self.tabScheme)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bttnNewColor.sizePolicy().hasHeightForWidth())
        self.bttnNewColor.setSizePolicy(sizePolicy)
        self.bttnNewColor.setObjectName("bttnNewColor")
        self.gridLayout_4.addWidget(self.bttnNewColor, 4, 1, 1, 1)
        self.lstCylinders = QtWidgets.QListView(self.tabScheme)
        self.lstCylinders.setMaximumSize(QtCore.QSize(55, 16777215))
        self.lstCylinders.setObjectName("lstCylinders")
        self.gridLayout_4.addWidget(self.lstCylinders, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_10 = QtWidgets.QLabel(self.tabScheme)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_4.addWidget(self.label_10, 0, 2, 1, 1)
        self.lstColor = QtWidgets.QListView(self.tabScheme)
        self.lstColor.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lstColor.setObjectName("lstColor")
        self.gridLayout_4.addWidget(self.lstColor, 1, 1, 1, 1)
        self.bttnNewID = QtWidgets.QPushButton(self.tabScheme)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bttnNewID.sizePolicy().hasHeightForWidth())
        self.bttnNewID.setSizePolicy(sizePolicy)
        self.bttnNewID.setObjectName("bttnNewID")
        self.gridLayout_4.addWidget(self.bttnNewID, 4, 2, 1, 1)
        self.bttnDeleteColor = QtWidgets.QPushButton(self.tabScheme)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bttnDeleteColor.sizePolicy().hasHeightForWidth())
        self.bttnDeleteColor.setSizePolicy(sizePolicy)
        self.bttnDeleteColor.setObjectName("bttnDeleteColor")
        self.gridLayout_4.addWidget(self.bttnDeleteColor, 3, 1, 1, 1)
        self.lstID = QtWidgets.QListView(self.tabScheme)
        self.lstID.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lstID.setObjectName("lstID")
        self.gridLayout_4.addWidget(self.lstID, 1, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.tabScheme)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 0, 0, 1, 1)
        self.tblPositions = QtWidgets.QTableView(self.tabScheme)
        self.tblPositions.setObjectName("tblPositions")
        self.gridLayout_4.addWidget(self.tblPositions, 1, 3, 1, 1)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_12 = QtWidgets.QLabel(self.tabScheme)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_12.addWidget(self.label_12, 0, QtCore.Qt.AlignLeft)
        self.label_16 = QtWidgets.QLabel(self.tabScheme)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_12.addWidget(self.label_16, 0, QtCore.Qt.AlignRight)
        self.bttnCopyDown = QtWidgets.QPushButton(self.tabScheme)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bttnCopyDown.sizePolicy().hasHeightForWidth())
        self.bttnCopyDown.setSizePolicy(sizePolicy)
        self.bttnCopyDown.setObjectName("bttnCopyDown")
        self.horizontalLayout_12.addWidget(self.bttnCopyDown)
        self.bttnCopyUp = QtWidgets.QPushButton(self.tabScheme)
        self.bttnCopyUp.setObjectName("bttnCopyUp")
        self.horizontalLayout_12.addWidget(self.bttnCopyUp, 0, QtCore.Qt.AlignLeft)
        self.gridLayout_4.addLayout(self.horizontalLayout_12, 0, 3, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_4, 1, 0, 1, 2)
        self.buttonBox.raise_()
        self.gridWidget_2.raise_()
        self.horizontalWidget.raise_()
        self.tab.addTab(self.tabScheme, "")
        self.tabCellLines = QtWidgets.QWidget()
        self.tabCellLines.setObjectName("tabCellLines")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.tabCellLines)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.cellLinesTable = QtWidgets.QTableView(self.tabCellLines)
        self.cellLinesTable.setMaximumSize(QtCore.QSize(1100, 16777215))
        self.cellLinesTable.setSortingEnabled(True)
        self.cellLinesTable.setObjectName("cellLinesTable")
        self.horizontalLayout_13.addWidget(self.cellLinesTable)
        self.verticalFrame = QtWidgets.QFrame(self.tabCellLines)
        self.verticalFrame.setObjectName("verticalFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalFrame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.bttnAddCellLine = QtWidgets.QPushButton(self.verticalFrame)
        self.bttnAddCellLine.setMaximumSize(QtCore.QSize(120, 16777215))
        self.bttnAddCellLine.setObjectName("bttnAddCellLine")
        self.verticalLayout_2.addWidget(self.bttnAddCellLine, 0, QtCore.Qt.AlignTop)
        self.bttnDeleteCellLine = QtWidgets.QPushButton(self.verticalFrame)
        self.bttnDeleteCellLine.setMaximumSize(QtCore.QSize(120, 16777215))
        self.bttnDeleteCellLine.setObjectName("bttnDeleteCellLine")
        self.verticalLayout_2.addWidget(self.bttnDeleteCellLine)
        self.horizontalLayout_13.addWidget(self.verticalFrame, 0, QtCore.Qt.AlignTop)
        self.gridLayout_9.addLayout(self.horizontalLayout_13, 0, 0, 1, 1)
        self.tab.addTab(self.tabCellLines, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.verticalWidget = QtWidgets.QWidget(self.tab_2)
        self.verticalWidget.setObjectName("verticalWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalWidget1 = QtWidgets.QWidget(self.verticalWidget)
        self.horizontalWidget1.setObjectName("horizontalWidget1")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.horizontalWidget1)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_4 = QtWidgets.QLabel(self.horizontalWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_9.addWidget(self.label_4)
        self.lblVersion = QtWidgets.QLabel(self.horizontalWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblVersion.sizePolicy().hasHeightForWidth())
        self.lblVersion.setSizePolicy(sizePolicy)
        self.lblVersion.setText("")
        self.lblVersion.setObjectName("lblVersion")
        self.horizontalLayout_9.addWidget(self.lblVersion)
        self.verticalLayout.addWidget(self.horizontalWidget1, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.bttnCheckUpdates = QtWidgets.QPushButton(self.verticalWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bttnCheckUpdates.sizePolicy().hasHeightForWidth())
        self.bttnCheckUpdates.setSizePolicy(sizePolicy)
        self.bttnCheckUpdates.setObjectName("bttnCheckUpdates")
        self.verticalLayout.addWidget(self.bttnCheckUpdates)
        self.gridLayout_7.addWidget(self.verticalWidget, 0, 0, 1, 1, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.tab.addTab(self.tab_2, "")
        self.horizontalLayout.addWidget(self.tab)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.spnNumberStore, self.cmbDewarStore)
        MainWindow.setTabOrder(self.cmbDewarStore, self.bttnFindStorage)
        MainWindow.setTabOrder(self.bttnFindStorage, self.tblStoreCells)
        MainWindow.setTabOrder(self.tblStoreCells, self.bttnSelectAllStore)
        MainWindow.setTabOrder(self.bttnSelectAllStore, self.bttnDeselectAllStore)
        MainWindow.setTabOrder(self.bttnDeselectAllStore, self.bttnAnotherPositionStore)
        MainWindow.setTabOrder(self.bttnAnotherPositionStore, self.bttnNewCane)
        MainWindow.setTabOrder(self.bttnNewCane, self.bttnStore)
        MainWindow.setTabOrder(self.bttnStore, self.txtInitials)
        MainWindow.setTabOrder(self.txtInitials, self.spnPassageStore)
        MainWindow.setTabOrder(self.spnPassageStore, self.txtDate)
        MainWindow.setTabOrder(self.txtDate, self.txtComments)
        MainWindow.setTabOrder(self.txtComments, self.bttnAddCells)
        MainWindow.setTabOrder(self.bttnAddCells, self.txtEmailStore)
        MainWindow.setTabOrder(self.txtEmailStore, self.bttnEmailPositionsStore)
        MainWindow.setTabOrder(self.bttnEmailPositionsStore, self.tblRetreiveCells)
        MainWindow.setTabOrder(self.tblRetreiveCells, self.txtCellsRetreive)
        MainWindow.setTabOrder(self.txtCellsRetreive, self.bttnFindCells)
        MainWindow.setTabOrder(self.bttnFindCells, self.chkTrash)
        MainWindow.setTabOrder(self.chkTrash, self.bttnSelectAllRetreive)
        MainWindow.setTabOrder(self.bttnSelectAllRetreive, self.bttnDeselectAllRetreive)
        MainWindow.setTabOrder(self.bttnDeselectAllRetreive, self.bttnRetreive)
        MainWindow.setTabOrder(self.bttnRetreive, self.txtEmailRetreive)
        MainWindow.setTabOrder(self.txtEmailRetreive, self.bttnEmailPositionsRetreive)
        MainWindow.setTabOrder(self.bttnEmailPositionsRetreive, self.combo_Dewar)
        MainWindow.setTabOrder(self.combo_Dewar, self.bttnDeleteColor)
        MainWindow.setTabOrder(self.bttnDeleteColor, self.lstID)
        MainWindow.setTabOrder(self.lstID, self.bttnNewColor)
        MainWindow.setTabOrder(self.bttnNewColor, self.bttnDeleteID)
        MainWindow.setTabOrder(self.bttnDeleteID, self.bttnNewID)
        MainWindow.setTabOrder(self.bttnNewID, self.lstCylinders)
        MainWindow.setTabOrder(self.lstCylinders, self.lstColor)
        MainWindow.setTabOrder(self.lstColor, self.tblPositions)
        MainWindow.setTabOrder(self.tblPositions, self.bttnCheckUpdates)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Cells Database"))
        self.label_17.setText(_translate("MainWindow", "Database Location (can be IP address or computer name):"))
        self.label_18.setText(_translate("MainWindow", "Username:"))
        self.label_19.setText(_translate("MainWindow", "Password:"))
        self.checkBox.setText(_translate("MainWindow", "Save username"))
        self.checkBox_2.setText(_translate("MainWindow", "Save password"))
        self.checkBox_3.setText(_translate("MainWindow", "Connect on startup"))
        self.label_20.setText(_translate("MainWindow", "Database:"))
        self.bttnConnect.setText(_translate("MainWindow", "Connect"))
        self.tab.setTabText(self.tab.indexOf(self.tabDatabase), _translate("MainWindow", "Database"))
        self.cmbDewarStore.setItemText(0, _translate("MainWindow", "GR"))
        self.cmbDewarStore.setItemText(1, _translate("MainWindow", "WF"))
        self.label_8.setText(_translate("MainWindow", "Number of Positions"))
        self.bttnFindStorage.setText(_translate("MainWindow", "Find Storage"))
        self.label_5.setText(_translate("MainWindow", "Dewar"))
        self.bttnEmailPositionsStore.setText(_translate("MainWindow", "Email Positions"))
        self.bttnSelectAllStore.setText(_translate("MainWindow", "Select All"))
        self.bttnDeselectAllStore.setText(_translate("MainWindow", "Deselect All"))
        self.bttnAnotherPositionStore.setText(_translate("MainWindow", "Find Another Position"))
        self.bttnNewCane.setText(_translate("MainWindow", "New Cane"))
        self.bttnStore.setText(_translate("MainWindow", "Store"))
        self.label.setText(_translate("MainWindow", "Initials"))
        self.label_6.setText(_translate("MainWindow", "Cell Type"))
        self.label_2.setText(_translate("MainWindow", "Date"))
        self.txtDate.setInputMask(_translate("MainWindow", "99/99/9999"))
        self.label_7.setText(_translate("MainWindow", "Passage"))
        self.label_15.setText(_translate("MainWindow", "Comments"))
        self.bttnAddCells.setText(_translate("MainWindow", "Add Cells"))
        self.tab.setTabText(self.tab.indexOf(self.tabStore), _translate("MainWindow", "Store Cells"))
        self.label_3.setText(_translate("MainWindow", "Cell Type"))
        self.bttnFindCells.setText(_translate("MainWindow", "Find Cells"))
        self.chkTrash.setText(_translate("MainWindow", "Trashed"))
        self.bttnSelectAllRetreive.setText(_translate("MainWindow", "Select All"))
        self.bttnDeselectAllRetreive.setText(_translate("MainWindow", "Deselect All"))
        self.bttnRetreive.setText(_translate("MainWindow", "Retrieve"))
        self.bttnEmailPositionsRetreive.setText(_translate("MainWindow", "Email Positions"))
        self.tab.setTabText(self.tab.indexOf(self.tabRetreive), _translate("MainWindow", "Retreive Cells"))
        self.label_14.setText(_translate("MainWindow", "Dewar"))
        self.combo_Dewar.setItemText(0, _translate("MainWindow", "GR"))
        self.combo_Dewar.setItemText(1, _translate("MainWindow", "WF"))
        self.label_13.setText(_translate("MainWindow", "Changes:"))
        self.lblChanges.setText(_translate("MainWindow", "0"))
        self.lblBlue.setText(_translate("MainWindow", "Changed"))
        self.lblGreen.setText(_translate("MainWindow", "New"))
        self.label_11.setText(_translate("MainWindow", "Cane Color"))
        self.bttnDeleteID.setText(_translate("MainWindow", "Delete"))
        self.bttnNewColor.setText(_translate("MainWindow", "New"))
        self.label_10.setText(_translate("MainWindow", "Cane ID"))
        self.bttnNewID.setText(_translate("MainWindow", "New"))
        self.bttnDeleteColor.setText(_translate("MainWindow", "Delete"))
        self.label_9.setText(_translate("MainWindow", "Cylinders"))
        self.label_12.setText(_translate("MainWindow", "Positions"))
        self.label_16.setText(_translate("MainWindow", "Copy Columns:"))
        self.bttnCopyDown.setText(_translate("MainWindow", "⬇"))
        self.bttnCopyUp.setText(_translate("MainWindow", "⬆"))
        self.tab.setTabText(self.tab.indexOf(self.tabScheme), _translate("MainWindow", "Database Scheme"))
        self.bttnAddCellLine.setText(_translate("MainWindow", "Add"))
        self.bttnDeleteCellLine.setText(_translate("MainWindow", "Delete "))
        self.tab.setTabText(self.tab.indexOf(self.tabCellLines), _translate("MainWindow", "Cell Lines"))
        self.label_4.setText(_translate("MainWindow", "Current Version:"))
        self.bttnCheckUpdates.setText(_translate("MainWindow", "Check for Updates"))
        self.tab.setTabText(self.tab.indexOf(self.tab_2), _translate("MainWindow", "About"))
