# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'storecellsdialog.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_StoreCellsDialog(object):

    def setupUi(self, StoreCellsDialog):
        StoreCellsDialog.setObjectName("StoreCellsDialog")
        StoreCellsDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        StoreCellsDialog.resize(611, 466)
        StoreCellsDialog.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.buttonBox = QtWidgets.QDialogButtonBox(StoreCellsDialog)
        self.buttonBox.setGeometry(QtCore.QRect(240, 420, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayoutWidget = QtWidgets.QWidget(StoreCellsDialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(30, 22, 441, 131))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gridLayoutWidget.sizePolicy().hasHeightForWidth())
        self.gridLayoutWidget.setSizePolicy(sizePolicy)
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.combo_Dewar = QtWidgets.QComboBox(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_Dewar.sizePolicy().hasHeightForWidth())
        self.combo_Dewar.setSizePolicy(sizePolicy)
        self.combo_Dewar.setObjectName("combo_Dewar")
        self.combo_Dewar.addItem("")
        self.combo_Dewar.addItem("")
        self.gridLayout.addWidget(self.combo_Dewar, 3, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.txt_CellType = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.txt_CellType.setObjectName("txt_CellType")
        self.gridLayout.addWidget(self.txt_CellType, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.spinBox_Passage = QtWidgets.QSpinBox(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_Passage.sizePolicy().hasHeightForWidth())
        self.spinBox_Passage.setSizePolicy(sizePolicy)
        self.spinBox_Passage.setProperty("value", 1)
        self.spinBox_Passage.setObjectName("spinBox_Passage")
        self.gridLayout.addWidget(self.spinBox_Passage, 1, 1, 1, 1)
        self.spinBox_NumberOfCells = QtWidgets.QSpinBox(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_NumberOfCells.sizePolicy().hasHeightForWidth())
        self.spinBox_NumberOfCells.setSizePolicy(sizePolicy)
        self.spinBox_NumberOfCells.setProperty("value", 1)
        self.spinBox_NumberOfCells.setObjectName("spinBox_NumberOfCells")
        self.gridLayout.addWidget(self.spinBox_NumberOfCells, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.button_FindStorage = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_FindStorage.sizePolicy().hasHeightForWidth())
        self.button_FindStorage.setSizePolicy(sizePolicy)
        self.button_FindStorage.setObjectName("button_FindStorage")
        self.gridLayout.addWidget(self.button_FindStorage, 2, 2, 1, 1)
        self.chckbox_SameType = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.chckbox_SameType.setChecked(True)
        self.chckbox_SameType.setObjectName("chckbox_SameType")
        self.gridLayout.addWidget(self.chckbox_SameType, 3, 2, 1, 1)
        self.button_SelectAll = QtWidgets.QPushButton(StoreCellsDialog)
        self.button_SelectAll.setGeometry(QtCore.QRect(30, 390, 101, 32))
        self.button_SelectAll.setObjectName("button_SelectAll")
        self.button_DeselectAll = QtWidgets.QPushButton(StoreCellsDialog)
        self.button_DeselectAll.setGeometry(QtCore.QRect(130, 390, 101, 32))
        self.button_DeselectAll.setObjectName("button_DeselectAll")
        self.button_AnotherPosition = QtWidgets.QPushButton(StoreCellsDialog)
        self.button_AnotherPosition.setGeometry(QtCore.QRect(230, 390, 161, 32))
        self.button_AnotherPosition.setObjectName("button_AnotherPosition")
        self.button_Store = QtWidgets.QPushButton(StoreCellsDialog)
        self.button_Store.setGeometry(QtCore.QRect(480, 260, 113, 32))
        self.button_Store.setObjectName("button_Store")
        self.tableWidget = QtWidgets.QTableWidget(StoreCellsDialog)
        self.tableWidget.setGeometry(QtCore.QRect(30, 170, 440, 211))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.tableWidget.verticalHeader().setVisible(True)

        self.retranslateUi(StoreCellsDialog)
        self.buttonBox.accepted.connect(StoreCellsDialog.accept)
        self.buttonBox.rejected.connect(StoreCellsDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(StoreCellsDialog)

    def retranslateUi(self, StoreCellsDialog):
        _translate = QtCore.QCoreApplication.translate
        StoreCellsDialog.setWindowTitle(_translate("StoreCellsDialog", "Store Cells"))
        self.combo_Dewar.setItemText(0, _translate("StoreCellsDialog", "GR"))
        self.combo_Dewar.setItemText(1, _translate("StoreCellsDialog", "WF"))
        self.label_3.setText(_translate("StoreCellsDialog", "Dewar"))
        self.label.setText(_translate("StoreCellsDialog", "Cell Type"))
        self.label_2.setText(_translate("StoreCellsDialog", "Passage"))
        self.label_4.setText(_translate("StoreCellsDialog", "Number of Cells"))
        self.button_FindStorage.setText(_translate("StoreCellsDialog", "Find Storage"))
        self.chckbox_SameType.setText(_translate("StoreCellsDialog", "Store near cells of the same type"))
        self.button_SelectAll.setText(_translate("StoreCellsDialog", "Select All"))
        self.button_DeselectAll.setText(_translate("StoreCellsDialog", "Deselect All"))
        self.button_AnotherPosition.setText(_translate("StoreCellsDialog", "Find Another Position"))
        self.button_Store.setText(_translate("StoreCellsDialog", "Store"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("StoreCellsDialog", "Dewar"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("StoreCellsDialog", "Cane Color"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("StoreCellsDialog", "Cane ID"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("StoreCellsDialog", "Position"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    StoreCellsDialog = QtWidgets.QDialog()
    ui = Ui_StoreCellsDialog()
    ui.setupUi(StoreCellsDialog)
    StoreCellsDialog.show()
    sys.exit(app.exec_())

